name: PlayerDeathCoords
version: '${project.version}'
main: one.crafters.playerdeathcoords.PlayerDeathCoords
api-version: 1.19
authors: [ Plexiate ]
description: Sends the coords of player deaths to discord using a webhook.
website: https://crafters.one
commands:
    pdc:
      description: Additional commands for Player Death Coords.
permissions:
  playerdeathcoords.reload:
    description: Allows the user to reload the config for Player Death Coords.
    default: op
